
services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"  # API port
      - "9001:9001"  # Console port
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: access_key
      MINIO_ROOT_PASSWORD: secret_key
      MINIO_BROWSER_REDIRECT_URL: http://localhost:9001
      MINIO_SERVER_URL: http://localhost:9000
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: always

  createbuckets:
    image: minio/mc
    container_name: createbuckets
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until mc alias set myminio http://minio:9000 access_key secret_key; do
        echo 'Waiting for MinIO to be ready...'
        sleep 5
      done &&
      mc mb myminio/food-panda-vendors &&
      mc ls myminio/food-panda-vendors &&
      echo 'Bucket created successfully' &&
      exit 0;
      "

  foodpanda-etl:
    container_name: foodpanda-etl
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data:rw
    environment:
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=access_key
      - MINIO_SECRET_KEY=secret_key
      - USER_LOGIN=docker_user
      - OUTPUT_DIR=/app/data
    working_dir: /app
    depends_on:
      minio:
        condition: service_healthy
      createbuckets:
        condition: service_completed_successfully

volumes:
  minio_data: