cities:
  - "69036"  # Example city ID

minio:
  endpoint: "http://localhost:9000"
  access_key: "access_key"
  secret_key: "secret_key"
  bucket: "food-panda-vendors"
  region: "us-east-1"
api:
  restaurant_url: "https://disco.deliveryhero.io/listing/api/v1/pandora/vendors"
  vendor_url: "https://pk.fd-api.com/api/v5/vendors"
  review_url: "https://reviews-api-pk.fd-api.com/ratings-distribution/vendor"
  headers:
    perseus-client-id: "1737108613136.802524900772077665.hi5re1m8x0"
    perseus-session-id: "1741721494639.068659692962093299.uzsw4zna3p"
    x-disco-client-id: "web"
    x-fp-api-key: "volo"
    x-pd-language-id: "1"
  base_params:
    configuration: ""
    country: "pk"
    language_id: "1"
    sort: ""
    vertical: "restaurants"
