cities:
  - "69036"  # Example city ID

minio:
  endpoint: "http://localhost:9000"
  access_key: "access_key"
  secret_key: "secret_key"
  bucket: "food-panda-vendors"
  region: "us-east-1"
api:
  headers:
    perseus-client-id: "1737108613136.802524900772077665.hi5re1m8x0"
    perseus-session-id: "1741721494639.068659692962093299.uzsw4zna3p"
    x-disco-client-id: "web"
    x-fp-api-key: "volo"
    x-pd-language-id: "1"
